set(LLNL_URL http://uvcdat.llnl.gov/cdat/resources)
set(WGET_MAJOR 1)
set(WGET_MINOR 16)
set(WGET_PATCH)
set(WGET_URL http://ftp.gnu.org/gnu/wget/)
set(WGET_GZ wget-${WGET_MAJOR}.${WGET_MINOR}.tar.gz)
set(WGET_MD5 293a37977c41b5522f781d3a3a078426)
set(WGET_SOURCE ${WGET_URL}/${WGET_GZ})

add_cdat_package(Wget "" "Build Wget" SYSTEM)

set (nm WGET)
string(TOUPPER ${nm} uc_nm)
set(${uc_nm}_VERSION ${${nm}_MAJOR}.${${nm}_MINOR})
if(CDAT_BUILD_WGET)
  if(WIN32)
    set(WGET_EXECUTABLE ${cdat_EXTERNALS}/bin/wget.exe)
  else()
    set(WGET_EXECUTABLE ${cdat_EXTERNALS}/bin/wget)
  endif()
endif()
if (${WGET_EXECUTABLE} STREQUAL "WGET_EXECUTABLE-NOTFOUND")
    set(WGET_EXECUTABLE ${cdat_EXTERNALS}/bin/wget)
endif()
message("[INFO] WGET_EXECUTABLE is set to ${WGET_EXECUTABLE}")

set(HASWGET ${WGET_EXECUTABLE})

